### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 14730: character maps to <undefined>

### ISSUE THREAD

**Issue by Rouzax** [willforde/mkvstrip#12]
Have an episode that gives an error, I think it is the Chinese characters 
```
Searching for MKV files to process.
Warning: This may take some time...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python37\lib\subprocess.py", line 1238, in _readerthread
    buffer.append(fh.read())
  File "C:\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 14730: character maps to <undefined>

Traceback (most recent call last):
  File "C:\GitHub\mkvstrip\mkvstrip.py", line 406, in <module>
    main()
  File "C:\GitHub\mkvstrip\mkvstrip.py", line 62, in wrapper
    func(*args, **kwargs)
  File "C:\GitHub\mkvstrip\mkvstrip.py", line 400, in main
    mkv_obj = MKVFile(mkv_file)
  File "C:\GitHub\mkvstrip\mkvstrip.py", line 232, in __init__
    stdout, _ = process.communicate(timeout=10)
  File "C:\Python37\lib\subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python37\lib\subprocess.py", line 1288, in _communicate
    stdout = stdout[0]
IndexError: list index out of range
```

This is the MediaInfo
```
General
Unique ID                                : 143997547468014760918389400065283668341 (0x6C54EB3A52D62114E289E0B2B0573975)
Complete name                            : C:\TEMP\Torrent\PROCD\test\The.Marvelous.Mrs.Maisel.S03E04.2160p.AMZN.WEBRip.DDP5.1.x264-NTb.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 9.75 GiB
Duration                                 : 48 min 5 s
Overall bit rate                         : 29.0 Mb/s
Encoded date                             : UTC 2019-12-09 14:06:27
Writing application                      : mkvmerge v32.0.0 ('Astral Progressions') 64-bit
Writing library                          : libebml v1.3.7 + libmatroska v1.5.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 48 min 5 s
Bit rate                                 : 28.4 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.143
Stream size                              : 9.53 GiB (98%)
Writing library                          : x264 core 158 r2984+47 456d10a t_mod_New [0-bit@all X86_64]
Encoding settings                        : cabac=1 / ref=5 / deblock=1:-3:-3 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / fade_compensate=0.00 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=48 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc=crf / mbtree=0 / crf=18.0000 / qcomp=0.60 / qpmin=0:0:0 / qpmax=69:69:69 / qpstep=4 / ip_ratio=1.30 / pb_ratio=1.20 / aq=3:0.80 / aq-sensitivity=10.00 / aq-factor=1.00:1.00:1.00 / aq2=0 / aq3=0
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 48 min 5 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 220 MiB (2%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 179 b/s
Count of elements                        : 1042
Stream size                              : 60.3 KiB (0%)
Language                                 : Arabic
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 107 b/s
Count of elements                        : 1040
Stream size                              : 36.2 KiB (0%)
Language                                 : Danish
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 5
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 50 s
Bit rate                                 : 97 b/s
Count of elements                        : 778
Stream size                              : 32.8 KiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 6
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 47 min 47 s
Bit rate                                 : 120 b/s
Count of elements                        : 1303
Stream size                              : 42.2 KiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : No
Forced                                   : No

Text #5
ID                                       : 7
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 112 b/s
Count of elements                        : 1041
Stream size                              : 37.9 KiB (0%)
Title                                    : Latinoamérica
Language                                 : Spanish
Default                                  : No
Forced                                   : No

Text #6
ID                                       : 8
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 113 b/s
Count of elements                        : 1037
Stream size                              : 38.3 KiB (0%)
Title                                    : España
Language                                 : Spanish
Default                                  : No
Forced                                   : No

Text #7
ID                                       : 9
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 98 b/s
Count of elements                        : 1040
Stream size                              : 33.1 KiB (0%)
Language                                 : Finnish
Default                                  : No
Forced                                   : No

Text #8
ID                                       : 10
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 97 b/s
Count of elements                        : 1041
Stream size                              : 32.9 KiB (0%)
Language                                 : French
Default                                  : No
Forced                                   : No

Text #9
ID                                       : 11
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 170 b/s
Count of elements                        : 1042
Stream size                              : 57.3 KiB (0%)
Language                                 : Hebrew
Default                                  : No
Forced                                   : No

Text #10
ID                                       : 12
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 280 b/s
Count of elements                        : 1042
Stream size                              : 94.4 KiB (0%)
Language                                 : Hindi
Default                                  : No
Forced                                   : No

Text #11
ID                                       : 13
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 86 b/s
Count of elements                        : 1042
Stream size                              : 29.1 KiB (0%)
Language                                 : Indonesian
Default                                  : No
Forced                                   : No

Text #12
ID                                       : 14
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 108 b/s
Count of elements                        : 1040
Stream size                              : 36.7 KiB (0%)
Language                                 : Italian
Default                                  : No
Forced                                   : No

Text #13
ID                                       : 15
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 50 s
Bit rate                                 : 79 b/s
Count of elements                        : 1034
Stream size                              : 26.6 KiB (0%)
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Text #14
ID                                       : 16
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 116 b/s
Count of elements                        : 1042
Stream size                              : 39.2 KiB (0%)
Language                                 : Korean
Default                                  : No
Forced                                   : No

Text #15
ID                                       : 17
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 109 b/s
Count of elements                        : 1041
Stream size                              : 36.7 KiB (0%)
Language                                 : Norwegian Bokmal
Default                                  : No
Forced                                   : No

Text #16
ID                                       : 18
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 94 b/s
Count of elements                        : 1041
Stream size                              : 31.8 KiB (0%)
Language                                 : Dutch
Default                                  : No
Forced                                   : No

Text #17
ID                                       : 19
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 84 b/s
Count of elements                        : 1037
Stream size                              : 28.3 KiB (0%)
Language                                 : Polish
Default                                  : No
Forced                                   : No

Text #18
ID                                       : 20
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 108 b/s
Count of elements                        : 1042
Stream size                              : 36.4 KiB (0%)
Language                                 : Portuguese
Default                                  : No
Forced                                   : No

Text #19
ID                                       : 21
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 188 b/s
Count of elements                        : 1041
Stream size                              : 63.4 KiB (0%)
Language                                 : Russian
Default                                  : No
Forced                                   : No

Text #20
ID                                       : 22
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 110 b/s
Count of elements                        : 1040
Stream size                              : 37.1 KiB (0%)
Language                                 : Swedish
Default                                  : No
Forced                                   : No

Text #21
ID                                       : 23
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 340 b/s
Count of elements                        : 1042
Stream size                              : 115 KiB (0%)
Language                                 : Tamil
Default                                  : No
Forced                                   : No

Text #22
ID                                       : 24
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 285 b/s
Count of elements                        : 1042
Stream size                              : 96.1 KiB (0%)
Language                                 : Telugu
Default                                  : No
Forced                                   : No

Text #23
ID                                       : 25
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 256 b/s
Count of elements                        : 1042
Stream size                              : 86.3 KiB (0%)
Language                                 : Thai
Default                                  : No
Forced                                   : No

Text #24
ID                                       : 26
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 95 b/s
Count of elements                        : 1042
Stream size                              : 32.1 KiB (0%)
Language                                 : Turkish
Default                                  : No
Forced                                   : No

Text #25
ID                                       : 27
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 110 b/s
Count of elements                        : 1042
Stream size                              : 37.3 KiB (0%)
Title                                    : 中文（简体）
Language                                 : Chinese
Default                                  : No
Forced                                   : No

Text #26
ID                                       : 28
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 45 min 58 s
Bit rate                                 : 100 b/s
Count of elements                        : 1042
Stream size                              : 33.9 KiB (0%)
Title                                    : 中文（繁體）
Language                                 : Chinese
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:Amazon Original
00:00:05.000                             : en:Midge has a good show
00:01:54.000                             : en:Title Sequence
00:01:59.000                             : en:A night out in Vegas
00:06:55.000                             : en:Adjusting to a new living situation
00:09:49.000                             : en:Midge's first paycheck
00:14:50.000                             : en:Mei brings a gift
00:18:29.000                             : en:Early morning wake up call
00:20:10.000                             : en:A flight to Vegas
00:21:46.000                             : en:Susie comes home to New York for meetings
00:25:39.000                             : en:Joel arrives in Vegas
00:26:26.000                             : en:Scheduling civil unrest
00:28:37.000                             : en:Comedy and drama come together
00:33:35.000                             : en:A night in Vegas together
00:36:56.000                             : en:A rough morning after
00:43:30.000                             : en:Ready to leave Vegas
00:46:05.000                             : en:End Credits
```

**Comment by Rouzax** [comment]
This is is the json output from MKVMerge
```
C:\TEMP\Torrent\PROCD\test>c:\GitHub\MKVmergev40\mkvmerge.exe -i -F json C:\TEMP\Torrent\PROCD\test\The.Marvelous.Mrs.Maisel.S03E04.2160p.AMZN.WEBRip.DDP5.1.x264-NTb.mkv
{
  "attachments": [],
  "chapters": [
    {
      "num_entries": 17
    }
  ],
  "container": {
    "properties": {
      "container_type": 17,
      "date_local": "2019-12-09T15:06:27+01:00",
      "date_utc": "2019-12-09T14:06:27Z",
      "duration": 2885184000000,
      "is_providing_timestamps": true,
      "muxing_application": "libebml v1.3.7 + libmatroska v1.5.0",
      "segment_uid": "6c54eb3a52d62114e289e0b2b0573975",
      "writing_application": "mkvmerge v32.0.0 ('Astral Progressions') 64-bit"
    },
    "recognized": true,
    "supported": true,
    "type": "Matroska"
  },
  "errors": [],
  "file_name": "C:\\TEMP\\Torrent\\PROCD\\test\\The.Marvelous.Mrs.Maisel.S03E04.2160p.AMZN.WEBRip.DDP5.1.x264-NTb.mkv",
  "global_tags": [],
  "identification_format_version": 12,
  "track_tags": [],
  "tracks": [
    {
      "codec": "MPEG-4p10/AVC/H.264",
      "id": 0,
      "properties": {
        "codec_id": "V_MPEG4/ISO/AVC",
        "codec_private_data": "01640033ffe1001867640033acc8600f0010fa1000003e90000bb808f18319a001000668e978232c8b",
        "codec_private_length": 41,
        "default_duration": 41708333,
        "default_track": true,
        "display_dimensions": "3840x2160",
        "display_unit": 0,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 0,
        "number": 1,
        "packetizer": "mpeg4_p10_video",
        "pixel_dimensions": "3840x2160",
        "uid": 1
      },
      "type": "video"
    },
    {
      "codec": "E-AC-3",
      "id": 1,
      "properties": {
        "audio_channels": 6,
        "audio_sampling_frequency": 48000,
        "codec_id": "A_EAC3",
        "codec_private_length": 0,
        "default_duration": 32000000,
        "default_track": true,
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 0,
        "number": 2,
        "uid": 7598282350680697993
      },
      "type": "audio"
    },
    {
      "codec": "SubRip/SRT",
      "id": 2,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "ara",
        "minimum_timestamp": 6132000000,
        "number": 3,
        "text_subtitles": true,
        "uid": 1346360102484121857
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 3,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "dan",
        "minimum_timestamp": 6132000000,
        "number": 4,
        "text_subtitles": true,
        "uid": 5946573262706404671
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 4,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "ger",
        "minimum_timestamp": 6132000000,
        "number": 5,
        "text_subtitles": true,
        "uid": 12454625561594167388
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 5,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 6006000000,
        "number": 6,
        "text_subtitles": true,
        "track_name": "SDH",
        "uid": 8820688594205936507
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 6,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "spa",
        "minimum_timestamp": 6132000000,
        "number": 7,
        "text_subtitles": true,
        "track_name": "Latinoamérica",
        "uid": 18022781649224009923
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 7,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "spa",
        "minimum_timestamp": 6132000000,
        "number": 8,
        "text_subtitles": true,
        "track_name": "España",
        "uid": 16665584571978680450
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 8,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "fin",
        "minimum_timestamp": 6132000000,
        "number": 9,
        "text_subtitles": true,
        "uid": 715520991079555232
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 9,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "fre",
        "minimum_timestamp": 6132000000,
        "number": 10,
        "text_subtitles": true,
        "uid": 13845745511297416075
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 10,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "heb",
        "minimum_timestamp": 6132000000,
        "number": 11,
        "text_subtitles": true,
        "uid": 10546922203967457608
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 11,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "hin",
        "minimum_timestamp": 6132000000,
        "number": 12,
        "text_subtitles": true,
        "uid": 2147460790713716152
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 12,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "ind",
        "minimum_timestamp": 6132000000,
        "number": 13,
        "text_subtitles": true,
        "uid": 6257038055527974443
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 13,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "ita",
        "minimum_timestamp": 6132000000,
        "number": 14,
        "text_subtitles": true,
        "uid": 13397492009674814578
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 14,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "jpn",
        "minimum_timestamp": 6090000000,
        "number": 15,
        "text_subtitles": true,
        "uid": 14274721694157817980
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 15,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "kor",
        "minimum_timestamp": 6132000000,
        "number": 16,
        "text_subtitles": true,
        "uid": 15030910858526312017
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 16,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "nob",
        "minimum_timestamp": 6132000000,
        "number": 17,
        "text_subtitles": true,
        "uid": 17444794285121263146
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 17,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "dut",
        "minimum_timestamp": 6132000000,
        "number": 18,
        "text_subtitles": true,
        "uid": 14598986218694509959
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 18,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "pol",
        "minimum_timestamp": 6132000000,
        "number": 19,
        "text_subtitles": true,
        "uid": 4091315132573308147
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 19,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "por",
        "minimum_timestamp": 6132000000,
        "number": 20,
        "text_subtitles": true,
        "uid": 4095853003906093358
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 20,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "rus",
        "minimum_timestamp": 6132000000,
        "number": 21,
        "text_subtitles": true,
        "uid": 14402392718396559158
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 21,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "swe",
        "minimum_timestamp": 6132000000,
        "number": 22,
        "text_subtitles": true,
        "uid": 12893132703267361336
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 22,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "tam",
        "minimum_timestamp": 6132000000,
        "number": 23,
        "text_subtitles": true,
        "uid": 4512987016009394961
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 23,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "tel",
        "minimum_timestamp": 6132000000,
        "number": 24,
        "text_subtitles": true,
        "uid": 17260419018647764994
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 24,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "tha",
        "minimum_timestamp": 6132000000,
        "number": 25,
        "text_subtitles": true,
        "uid": 10199982097274642586
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 25,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "tur",
        "minimum_timestamp": 6132000000,
        "number": 26,
        "text_subtitles": true,
        "uid": 8953148000444027709
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 26,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "chi",
        "minimum_timestamp": 6132000000,
        "number": 27,
        "text_subtitles": true,
        "track_name": "中文（简体）",
        "uid": 1277716898034955601
      },
      "type": "subtitles"
    },
    {
      "codec": "SubRip/SRT",
      "id": 27,
      "properties": {
        "codec_id": "S_TEXT/UTF8",
        "codec_private_length": 0,
        "default_track": false,
        "enabled_track": true,
        "encoding": "UTF-8",
        "forced_track": false,
        "language": "chi",
        "minimum_timestamp": 6132000000,
        "number": 28,
        "text_subtitles": true,
        "track_name": "中文（繁體）",
        "uid": 5821699481651883632
      },
      "type": "subtitles"
    }
  ],
  "warnings": []
}
```

**Comment by Rouzax** [comment]
Figured a workaround for this on line 223 change it to
```
        process = subprocess.Popen(command, stdout=subprocess.PIPE, universal_newlines=True, encoding="utf8", errors='ignore')
```
